# Generated by Django 5.0.7 on 2024-09-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_lecturer_staff_id_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancetoken',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
