# Generated by Django 5.0.7 on 2026-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendance_require_two_factor_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='require_two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='attendancestudent',
            index=models.Index(fields=['attendance', 'student'], name='attendance__attenda_7bc322_idx'),
        ),
    ]
