# Generated by Django 5.0.7 on 2026-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_student_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration_hours',
            field=models.IntegerField(default=2),
        ),
    ]
