# Generated by Django 5.0.7 on 2026-03-05 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_duration_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancetoken',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_26d5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancetoken',
            index=models.Index(fields=['course', 'is_active'], name='attendance__course__fcf8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['lecturer', 'is_active'], name='attendance__lecture_8fd34c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_980990_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student'], name='attendance__student_3110f3_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course'], name='attendance__course__b91ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['department'], name='attendance__departm_a2c31b_idx'),
        ),
    ]
