# Generated by Django 5.2 on 2026-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_attendance_attendance__created_a6132d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Notification Token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Notification Token', max_length=255, null=True),
        ),
    ]
