# Generated by Copilot on 2026-05-15

import secrets
import string

from django.db import migrations


JOIN_CODE_LENGTH = 6
JOIN_CODE_ALPHABET = string.ascii_uppercase + string.digits


def _generate_join_code(used_codes, course_codes, max_attempts=50):
    for _ in range(max_attempts):
        code = ''.join(secrets.choice(JOIN_CODE_ALPHABET) for _ in range(JOIN_CODE_LENGTH))
        if code not in used_codes and code not in course_codes:
            used_codes.add(code)
            return code
    raise RuntimeError("Unable to generate a unique join code.")


def populate_join_codes(apps, schema_editor):
    Course = apps.get_model('attendance', 'Course')
    used_codes = set()
    course_codes = {
        code.strip().upper()
        for code in Course.objects.values_list('course_code', flat=True)
        if code
    }

    for course in Course.objects.all().order_by('id'):
        normalized = (course.join_code or '').strip().upper()
        if not normalized or normalized in used_codes or normalized in course_codes:
            normalized = _generate_join_code(used_codes, course_codes)
            course.join_code = normalized
            course.save(update_fields=['join_code'])
            continue

        if normalized != course.join_code:
            course.join_code = normalized
            course.save(update_fields=['join_code'])
        used_codes.add(normalized)


def reverse_join_codes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_alter_student_student_id_max_length'),
    ]

    operations = [
        migrations.RunPython(populate_join_codes, reverse_join_codes),
    ]
